### ISSUE TITLE
"DIE: Sequences must be a complete set of codons, i.e., the nucleotide length"

### ISSUE THREAD

**Issue by Enrique-SC** [chasewnelson/OLGenie#1]
Hello, 

I'm interested in using your program for my project. However when I run it  this appears:

"DIE: Sequences must be a complete set of codons, i.e., the nucleotide length### must be evenly divisible by 3. Instead, the length is 1204. TERMINATED."

The aligment of my overlapping gene has a lenght of 1203 but I don't know why it says that has 1204. Do you know wich could be the reasons and how can I fix this? Do I have to eliminate stop codons or something like Datamonkey?

Thank you in advance.

**Comment by singing-scientist** [comment]
Thanks very much for using OLGenie, @Enrique-SC! There is no problem with STOP codons, which the OLGenie method simply ignores. Instead, I think it is very likely there are 'hidden' (non-ASCII) characters at the end of each line, such as something introduced by a program like Microsoft Words, or else Windows line-endings. If you'd like to share the file I can certainly investigate for you.

Yours,
Chase

**Comment by singing-scientist** [comment]
Dear @Enrique-SC: has this issue been resolved?

**Comment by singing-scientist** [comment]
Given 20 days of silence, I will now close this issue. Please feel free to re-open if the problem has not been resolved!
