### ISSUE TITLE
Issues Encountered While Replicating Article Results Using Provided Example File

### ISSUE THREAD

**Issue by Little-Deer1** [chasewnelson/OLGenie#5]
Hello, I am attempting to replicate the results from the article using the example file you provided: HIV1_env_BLAST.fa, but I have encountered a few issues.

1. When I aligned the HIV1_env_BLAST.fa file by codon, I obtained a total of 890 codons, whereas the article mentions a count of 1355 codons. What could be the reason for this difference, and whether it might have any implications on the final results?

2. In Figure 3c of the article, the y-axis represents loge(1/p). I would appreciate it if you could clarify which value in the output of OLGenie_sliding_windows.R corresponds to the P mentioned here. Is it "sw_boot_dN_over_dS_P"? Additionally, if many of the "sw_boot_dN_over_dS_P" values are Inf, could you suggest a method for handling them appropriately in order to present them on the graph?

**Comment by singing-scientist** [comment]
Greetings @Little-Deer1 ! Thanks for the questions and sorry for the confusion. 

1. The EXAMPLE_INPUT files on the GitHub are examples for making sure OLGenie runs, but are not the publication datasets. For the full data (careful: some files are huge), please see the supplementary material indicated in the manuscript: https://zenodo.org/records/3575391. Keep in mind there are two HIV datasets. For the BLAST codon alignment (CAL), you want HIV1_env.tar.gz / HIV1_env_CAL.fasta (4065 nt / 3 = 1355 codons).

2. The p-value being shown is boot_dN_m_dS_P, which stands for "dN minus dS" (see the [documentation here]( https://github.com/chasewnelson/OLGenie/tree/master?tab=readme-ov-file#bootstrap-output), where this is indicated as the **_Recommended test_**). This is actually implied by the null hypothesis stated in the Fig. 3c legend, i.e., dNN - dNS, so the Z test p value refers to dN - dS = 0 (I know that's hard to spot!). It's been awhile, but I believe these results can be found in the same supplementary folder as above, e.g., in the file HIV1_env.tar.gz / HIV1_env_BLAST_OLGenie_windows_sas12.txt for the sas12 results. Here I have named the columns (hopefully) more intuitively, e.g., "dNNdSN_sw_P" for the p value relevant to the null dNN - dSN = 0.

Let me know if that helps!
Chase

**Comment by Little-Deer1** [comment]
Thank you very much! That's really helpful.

**Comment by Little-Deer1** [comment]
Thank you very much! That's really helpful.













-----原始邮件-----
发件人:"Chase W. Nelson 倪誠志" ***@***.***>
发送时间:2024-11-26 18:00:39 (星期二)
收件人: chasewnelson/OLGenie ***@***.***>
抄送: Little-Deer1 ***@***.***>, Mention ***@***.***>
主题: Re: [chasewnelson/OLGenie] Issues Encountered While Replicating Article Results Using Provided Example File (Issue #5)






Greetings @Little-Deer1 ! Thanks for the questions and sorry for the confusion.

The EXAMPLE_INPUT files on the GitHub are examples for making sure OLGenie runs, but are not the publication datasets. For the full data (careful: some files are huge), please see the supplementary material indicated in the manuscript: https://zenodo.org/records/3575391. Keep in mind there are two HIV datasets. For the BLAST codon alignment (CAL), you want HIV1_env.tar.gz / HIV1_env_CAL.fasta (4065 nt / 3 = 1355 codons).

The p-value being shown is boot_dN_m_dS_P, which stands for "dN minus dS" (see the documentation here, where this is indicated as the Recommended test). This is actually implied by the null hypothesis stated in the Fig. 3c legend, i.e., dNN - dNS, so the Z test p value refers to dN - dS = 0 (I know that's hard to spot!). It's been awhile, but I believe these results can be found in the same supplementary folder as above, e.g., in the file HIV1_env.tar.gz / HIV1_env_BLAST_OLGenie_windows_sas12.txt for the sas12 results. Here I have named the columns (hopefully) more intuitively, e.g., "dNNdSN_sw_P" for the p value relevant to the null dNN - dSN = 0.

Let me know if that helps!
Chase

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>


TRANSLATE with x
English
| Arabic | Hebrew | Polish |
| Bulgarian | Hindi | Portuguese |
| Catalan | Hmong Daw | Romanian |
| Chinese Simplified | Hungarian | Russian |
| Chinese Traditional | Indonesian | Slovak |
| Czech | Italian | Slovenian |
| Danish | Japanese | Spanish |
| Dutch | Klingon | Swedish |
| English | Korean | Thai |
| Estonian | Latvian | Turkish |
| Finnish | Lithuanian | Ukrainian |
| French | Malay | Urdu |
| German | Maltese | Vietnamese |
| Greek | Norwegian | Welsh |
| Haitian Creole | Persian | |
TRANSLATE with
COPY THE URL BELOW
Back
EMBED THE SNIPPET BELOW IN YOUR SITE
" onclick="this.select()" >="" <="" div="">
Enable collaborative features and customize widget: Bing Webmaster Portal
Back












------------
Tang Xiaolu
School of Life Sciences
Peking University
Beijing, China, 100871

TRANSLATE with x
English
| Arabic | Hebrew | Polish |
| Bulgarian | Hindi | Portuguese |
| Catalan | Hmong Daw | Romanian |
| Chinese Simplified | Hungarian | Russian |
| Chinese Traditional | Indonesian | Slovak |
| Czech | Italian | Slovenian |
| Danish | Japanese | Spanish |
| Dutch | Klingon | Swedish |
| English | Korean | Thai |
| Estonian | Latvian | Turkish |
| Finnish | Lithuanian | Ukrainian |
| French | Malay | Urdu |
| German | Maltese | Vietnamese |
| Greek | Norwegian | Welsh |
| Haitian Creole | Persian | |
TRANSLATE with
COPY THE URL BELOW
Back
EMBED THE SNIPPET BELOW IN YOUR SITE
" on_click="this.select()" >="" <="" div="">
Enable collaborative features and customize widget: Bing Webmaster Portal
Back

**Comment by singing-scientist** [comment]
My pleasure!
